[package]
name = "smallvec-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
#smallvec = { git = "https://github.com/servo/rust-smallvec", tag = "v0.6.9" }  # VULNERABLE
smallvec = "0.6.10" #PATCHED
valgrind = "0.1"  # optional za detekciju

